### PR TITLE
mention Rserve, svSocket and RApache before plumber

### PR DESCRIPTION
**Pull request by daroczig**
I thought it would make sense to mention these implementations as well if `plumber` was named -- these have been around for many years and empowered many business (and hobby) applications.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Good call.  And maybe add the performant (and current, updated) [RestRserve](https://github.com/rexyai/RestRserve).

**Comment by daroczig** [comment]
Let me know what you think about the above commits and please do feel free to edit/remove any part -- I will also proof-read tomorrow (getting pretty late here), and again, sorry for the long delay with this!

**Comment by nuest** [comment]
Thanks @daroczig I'll merge now and ping you when I make any review-needy changes.

**Comment by daroczig** [comment]
Thank you very much :bowing_man:

**Comment by nuest** [comment]
Here are my edits (please check if meaning preserved) and a question: https://github.com/nuest/rockerverse-paper/commit/2a0e3a1e1d71a8b5b62aeafaebd24e4f406f952f

_When you "moved away from Debian testing", does that mean at a second stage you did not use `rocker/r-base` anymore?_

**Comment by daroczig** [comment]
> Here are my edits (please check if meaning preserved) and a question: 2a0e3a1

Thanks a lot for your time spent on that and all the improvements -- all changes look good.

One minor thing: I think I introduced a typo with "exteremely" -- probablt it's easier to fix on your end then me submitting a PR and asking for your review, but happy to do so, just ping me, please.

> When you "moved away from Debian testing", does that mean at a second stage you did not use rocker/r-base anymore?

Yeah, good question -- we actually moved to Ubuntu LTS but reusing many things from the Dockerfiles of `rocker/r-base` and eventually ended up with something like `rocker/r-ver`. We just needed more control over what gets updated when to reduce the risk with updates started independent from us.

**Pull request merged**
