### PR TITLE
Merging the googleCloudRunner references

### PR DESCRIPTION
**Pull request by MarkEdmondson1234**

### CODE REVIEW

**Comment by MarkEdmondson1234** [comment]
Thanks @nuest for updating all the correct references

**Comment by nuest** [comment]
@MarkEdmondson1234 Can you please add `googleCloudRunner` to the section about the clients, in just a short sentence and with a reference to the main paragraph where it is used?

**Comment by MarkEdmondson1234** [comment]
Hows that? @nuest

**Comment by nuest** [comment]
That's great - thanks!

**Pull request merged**
