### PR TITLE
Addition of the 'PrarieLearn' experience with rocker-pl

### PR DESCRIPTION
**Pull request by eddelbuettel**
This expands the 'teaching' section with a second block based on 'PrarieLearn' experience here at Illinois which seems similar (yet different) to the 'Dodona' approach at Ghent.

### CODE REVIEW

**Comment by nuest** [comment]
Thanks Dirk! I think this second example makes the educational use case much stronger.

**Comment by eddelbuettel** [comment]
Thanks for the quick merge.  @barbehenna kindly offered some help will try to give it the good old lookover as well, and I will revisit once more this eve.  We may have a minor refinement (to stress Docker/Rocker aspects) for you, with a bit of luck by tomorrow.

(Also: Alton, please meet Daniel; Daniel; please meet Alton.  As one should :tophat: :grinning: )

**Comment by nuest** [comment]
Hi @barbehenna :wave: 

@eddelbuettel I couldn't resist doing a little restructuring, and small changes to your text. I think this makes the use cases more accessible, see https://github.com/nuest/rockerverse-paper/commit/0ee3bde9814231d6f0d6a39e8d370ea84d4b8334

If you have a minor revision, just open the PR. I'll take care of the communication of the changes to the people who already "signed off", though I don't see an issue at all here - it's getting better not worse :-).

**Comment by eddelbuettel** [comment]
Great, and thanks for heads up. I'll rebuild and send that to Alton too!

**Comment by nuest** [comment]
Rebuild already done on Travis: https://nuest.github.io/rockerverse-paper/master.pdf

**Comment by eddelbuettel** [comment]
Locally too, while doing other work, and doing locally has its plusses:  ;-)

```sh
Output created: RJwrapper.pdf
Warning message:
LaTeX Warning: Label `workenvs' multiply defined.
LaTeX Warning: There were multiply-defined labels. 
```

Can you take care of that?

**Comment by nuest** [comment]
Well, a user would have to read the error output to take advantage of that plus :-) Fixed!

**Pull request merged**
